# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

env:
    - GHCVER=8.0.2
# Ensure necessary system libraries are present
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack config set system-ghc --global true
- export PATH=/opt/ghc/$GHCVER/bin:$PATH

script:
# Build the package, its tests, and its docs and run the tests
- stack build --no-terminal --skip-ghc-check --test --coverage

after_script:
#    - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-$GHCVER.tar.bz2 | tar -xj
    - stack install stack-hpc-coveralls-0.0.3.0
    - shc combined all